num1=10
num2=2
suma=num1+num2
resta=num1+num2
multiplicacion=num1*num2
division=num1/num2
print("suma:",suma)
print("resta:",resta)
print("multiplicacion:",multiplicacion)
print("division:",division)